version: '3.8'

services:
  s3:
    build:
      context: .
      dockerfile: ./docker/dockerfile.minio
    container_name: "s3"
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./docker/object_storage:/minio/storedData
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"

